{
 "title": "Embedded-Obersvability-Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Thing",
    "query": "SELECT device FROM \"visibility\".\"visibility\" WHERE time between ago(${timeRange}) and now() ORDER BY time DESC LIMIT 250 "
   },
   {
    "name": "AggregationInterval",
    "label": "Aggregation Interval",
    "query": "100ms, 1s, 5s, 10s, 20s, 30s, 1m, 3m, 5m, 15m, 30m, 45m, 60m"
   },
   {
    "name": "GGComponent",
    "label": "GG Component",
    "query": "CAN_Stats, FreeRTOSOS, FreeRTOSApp"
   },
   {
    "name": "timeRange",
    "label": "Time Range",
    "query": "1s,5s,15s,30s,1m,5m,10m,15m,30m,1h,6h,12h,1d"
   },
   {
    "name": "NucleusMetric",
    "query": "SELECT measure_name FROM \"visibility\".\"visibility\" WHERE name='ggTelemetry'"
   },
   {
    "name": "RTOSTask",
    "query": "SELECT \"rtos subtask\" FROM \"visibility\".\"visibility\" WHERE time between ago(360m) and now() ORDER BY time DESC LIMIT 1000 "
   }
  ]
 },
 "panels": [
  { "title": "CAN Component Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages Transmitted",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "rawQuery": "SELECT measure_value::bigint as Message_Transmitted, time FROM \"visibility\".\"visibility\" \nWHERE name='CAN_Stats' \nAND measure_name='MessagesTransmittedCount'\nAND time between ago(${timeRange}) and now() ORDER BY time DESC LIMIT 10\n"
    }
   ]
  },
  {
   "title": "FreeROTS Processing Response Time",
   "type": "xychart",
   "gridPos": { "h": 15, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "rawQuery": "SELECT measure_value::bigint as ResponseTime\nFROM \"visibility\".\"visibility\"  \nWHERE measure_name= 'ResponseTime' \nAND time between ago(${timeRange}) and now() ORDER BY time DESC LIMIT 250 "
    },
    {
     "rawQuery": "SELECT measure_value::bigint as CanTransmitted\nFROM \"visibility\".\"visibility\" \nWHERE measure_name= 'MessagesTransmittedCount'\nAND time between ago(${timeRange}) and now() ORDER BY time DESC LIMIT 250 \n"
    }
   ]
  },
  {
   "title": "Data Load",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "SELECT measure_value::double * 100 as Data_Load FROM \"visibility\".\"visibility\" \nWHERE name='CAN_Stats' \nAND measure_name='CANDataLoad' \nAND time between ago(${timeRange}) and now() ORDER BY time DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "SELECT measure_value::double as Data_Throughput\nFROM \"visibility\".\"visibility\" \nWHERE name='CAN_Stats' \nAND measure_name='CANDataThroughput' \nAND time between ago(${timeRange}) and now() ORDER BY time DESC LIMIT 1 "
    }
   ]
  },
  { "title": "FreeRTOS Component Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "FreeRTOS OS Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 17 },
   "targets": [
    {
     "database": "\"visibility\"",
     "measure": "AbsTime",
     "rawQuery": "SELECT measure_value::bigint as Scheduling_Latency, time FROM \"visibility\".\"visibility\" WHERE name='FreeRTOSOS' AND measure_name='SchedulingLatency' AND time between ago(${timeRange}) and now() ORDER BY time DESC LIMIT 250 ",
     "table": "\"visibility\""
    }
   ]
  },
  {
   "title": "Percent Time Spent on Task",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "SELECT measure_value::bigint as \"read\"\nFROM \"visibility\".\"visibility\"\nWHERE name= 'FreeRTOSApp' AND measure_name= 'AbsTime' and \"rtos subtask\"= 'readTask' \nAND time between ago(15m) and now() ORDER BY time DESC LIMIT 10"
    },
    {
     "rawQuery": "SELECT measure_value::bigint as \"write\"\nFROM \"visibility\".\"visibility\"\nWHERE name= 'FreeRTOSApp' AND measure_name= 'AbsTime' and \"rtos subtask\"= 'writeTask' \nAND time between ago(15m) and now() ORDER BY time DESC LIMIT 10"
    },
    {
     "database": "\"visibility\"",
     "measure": "AbsTime",
     "rawQuery": "SELECT measure_value::bigint as \"stats\"\nFROM \"visibility\".\"visibility\"\nWHERE name= 'FreeRTOSApp' AND measure_name= 'AbsTime' and \"rtos subtask\"= 'statsTask'\nAND time between ago(15m) and now() ORDER BY time DESC LIMIT 10",
     "table": "\"visibility\""
    }
   ]
  },
  {
   "title": "Mailbox Writes Success/Error",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "rawQuery": "SELECT measure_value::bigint as Success, time \nFROM \"visibility\".\"visibility\" WHERE name='FreeRTOSApp' \nAND measure_name='MailboxWriteSuccessCount' \nAND time between ago(15m) and now() ORDER BY time DESC LIMIT 10"
    },
    {
     "rawQuery": "SELECT measure_value::bigint as Error, time FROM \"visibility\".\"visibility\" WHERE name='FreeRTOSApp' AND measure_name='MailboxWriteErrorCount' AND time between ago(15m) and now() ORDER BY time DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "RTOS TASK: ${RTOSTask} Abs Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 24 },
   "targets": [
    {
     "rawQuery": "SELECT measure_value::bigint as AbsTime, time\nFROM \"visibility\".\"visibility\"\nWHERE name= 'FreeRTOSApp' AND measure_name= 'AbsTime' and \"rtos subtask\"= 'statsTask'"
    },
    {
     "rawQuery": "SELECT measure_value::bigint as AbsTime, time\nFROM \"visibility\".\"visibility\"\nWHERE name= 'FreeRTOSApp' AND measure_name= 'AbsTime' and \"rtos subtask\"= 'writeTask'"
    },
    {
     "rawQuery": "SELECT measure_value::bigint as AbsTime, time\nFROM \"visibility\".\"visibility\"\nWHERE name= 'FreeRTOSApp' AND measure_name= 'AbsTime' and \"rtos subtask\"= 'readTask'"
    }
   ]
  },
  {
   "title": "Priority ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawQuery": "SELECT measure_value::bigint as write_Priority, time\nFROM \"visibility\".\"visibility\"\nWHERE name= 'FreeRTOSApp' AND measure_name= 'Priority' and \"rtos subtask\"= 'writeTask' \nAND time between ago(${timeRange}) and now() ORDER BY time DESC LIMIT 10"
    },
    {
     "rawQuery": "SELECT measure_value::bigint as Read_Priority, time\nFROM \"visibility\".\"visibility\"\nWHERE name= 'FreeRTOSApp' AND measure_name= 'Priority' and \"rtos subtask\"= 'readTask' \nAND time between ago(${timeRange}) and now() ORDER BY time DESC LIMIT 10"
    },
    {
     "database": "\"visibility\"",
     "measure": "AbsTime",
     "rawQuery": "SELECT measure_value::bigint as Stats_Priority, time\nFROM \"visibility\".\"visibility\"\nWHERE name= 'FreeRTOSApp' AND measure_name= 'Priority' and \"rtos subtask\"= 'statsTask' \nAND time between ago(${timeRange}) and now() ORDER BY time DESC LIMIT 10",
     "table": "\"visibility\""
    }
   ]
  },
  {
   "title": "GreenGrass Component Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "repeat": "GGComponent",
   "collapsed": true,
   "panels": [
    {
     "title": "NUCLEUS METRIC: ${NucleusMetric}",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 15, "x": 0, "y": 11 },
     "targets": [
      {
       "database": "\"visibility\"",
       "measure": "AbsTime",
       "rawQuery": "SELECT time, if('${NucleusMetric}' = 'CpuUsage', measure_value::double, measure_value::bigint) AS ${NucleusMetric} \nFROM \"visibility\".\"visibility\" \nWHERE measure_name= '${NucleusMetric}'\nAND time between ago(${timeRange}) and now()",
       "table": "\"visibility\""
      }
     ]
    },
    {
     "title": "IPC time",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 9, "x": 15, "y": 11 },
     "targets": [
      {
       "rawQuery": "SELECT time, measure_value::bigint \nFROM \"visibility\".\"visibility\" \nWHERE name= 'GreengrassProcessing' \nAND measure_name='Time' \nAND time between ago(15m) and now() ORDER BY time DESC LIMIT 100"
      }
     ]
    }
   ]
  },
  { "title": "End to End Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Device, Greengrass, Cloud interaction latency. Component: ${GGComponent}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawQuery": "SELECT to_milliseconds(component_ts - device_ts) as device_to_component, time FROM \"visibility\".\"visibility\" \nWHERE name='${GGComponent}'\nAND time between ago(${timeRange}) and now() ORDER BY time DESC limit 10000\n\n"
    },
    {
     "rawQuery": "SELECT to_milliseconds((time - 4h) - component_ts) as component_to_cloud, time FROM \"visibility\".\"visibility\" \nWHERE name='${GGComponent}' \nAND time between ago(${timeRange}) and now() ORDER BY time DESC limit 10000\n\n"
    }
   ]
  },
  {
   "title": "Scheduling and Response Time Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "rawQuery": "with rT as (SELECT measure_value::bigint as responseTime\nFROM \"visibility\".\"visibility\" \nWHERE name='FreeRTOSApp' AND measure_name='ResponseTime'\nAND time between ago(${timeRange}) and now() ORDER BY time DESC limit 10000), \nsL as (SELECT time, measure_value::bigint as schedulingLatency\nFROM \"visibility\".\"visibility\" \nWHERE name='FreeRTOSOS' AND measure_name='SchedulingLatency'\nAND time between ago(${timeRange}) and now() ORDER BY time DESC limit 10000)\nSELECT BIN(time, ${AggregationInterval}), \navg(responseTime + schedulingLatency) as Sum FROM rT, sL \nGROUP BY BIN(time, ${AggregationInterval}) ORDER BY BIN(time, ${AggregationInterval})"
    }
   ]
  },
  {
   "title": "Rate of Transmission/Reception Change",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 42 },
   "targets": [
    {
     "rawQuery": "with agg AS (\n  SELECT array_agg(measure_value::bigint)[cardinality(array_agg(measure_value::bigint))] as laste,\n  array_agg(measure_value::bigint)[1] as firste,\n  BIN(time, ${AggregationInterval}) AS ts\n  FROM \"visibility\".\"visibility\" \nWHERE name='CAN_Stats' \nAND measure_name='MessagesTransmittedCount'\nAND time between ago(${timeRange}) and now()\nGROUP BY BIN(time, ${AggregationInterval}) \nORDER BY BIN(time, ${AggregationInterval})\n) SELECT ts AS time, IF (${AggregationInterval} = '1s', \n(laste-firste) / (SELECT extract(MINUTE FROM ${AggregationInterval})) as Rate_of_Change_Transmission,\n((laste-firste) / (SELECT extract(SECOND FROM ${AggregationInterval}))) as Rate_of_Change_Transmission) FROM agg\n"
    }
   ]
  }
 ]
}